apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot-hello
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        app: springboot-hello
        tier: backend
    spec:
      containers:
      - name: springboot-hello
        image: sonamsamdupkhangsar/springboot-docker:simple
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080
